export const personSchema = {
  name: 'person',
  properties: {
    _id: 'objectId',
    NNI: 'string?',
    _partition: 'string',
    birthDate: 'string?',
    createdAt: 'date?',
    createdById: 'objectId',
    firstName: 'string?',
    image: 'string?',
    lastName: 'string?',
    sex: 'string?',
    syncedAt: 'date?',
    updatedAt: 'date?',
    userId: 'string?',
    wilayaId: 'objectId?',
    moughataaId: 'objectId?',
    communeId: 'objectId?',
  },
  primaryKey: '_id',
};

export const userSchema = {
  name: 'user',
  properties: {
    _id: 'objectId',
    _partition: 'string',
    active: 'bool?',
    addedCount: 'int?',
    closedCommunes: 'string[]',
    communeId: 'objectId?',
    controllerId: 'objectId?',
    createdAt: 'date?',
    createdById: 'objectId?',
    excluded: 'int?',
    fullName: 'string?',
    id: 'string?',
    lastLoggedIn: 'date?',
    moughataaId: 'objectId?',
    nni: 'string?',
    operationId: 'objectId?',
    password: 'string?',
    person: 'user_person',
    personId: 'objectId?',
    phoneNumber: 'string?',
    categorie: 'string?',
    categorieDetails: 'string?',
    codeInitiative: 'string?',
    codeInitiativeParent: 'string?',
    nameInitiative: 'string?',
    role: 'string?',
    roleId: 'objectId?',
    syncedAt: 'date?',
    toBeSelectedCount: 'int?',
    updatedAt: 'date?',
    username: 'string?',
    wilayaId: 'objectId?',
    zonesIds: 'objectId[]',
    initiativeId: 'objectId?',
    initiativeName: 'string?',
    initiativeCode: 'string?',
    globCount: 'int?',
  },
  primaryKey: '_id',
};

export const user_personSchema = {
  name: 'user_person',
  embedded: true,
  properties: {
    NNI: 'string?',
    birthDate: 'string?',
    nationality: 'string?',
    documentNumber: 'string?',
    firstName: 'string?',
    image: 'string?',
    lastName: 'string?',
    sex: 'string?',
    updatedAt: 'date?',
  },
};

export const communeSchema = {
  name: 'commune',
  properties: {
    _id: 'objectId?',
    _partition: 'string',
    code_ons: 'string?',
    code_rs: 'string?',
    createdAt: 'date?',
    moughataa: 'string?',
    moughataa_id: 'objectId?',
    namear: 'string?',
    namefr_ons: 'string?',
    namefr_rs: 'string?',
    serverCreatedAt: 'date?',
    serverUpdatedAt: 'date?',
    updatedAt: 'date?',
    wilaya: 'string?',
    wilaya_id: 'objectId?',
    label: 'string?',
    value: 'string?',
  },
  primaryKey: '_id',
};

export const moughataaSchema = {
  name: 'moughataa',
  properties: {
    _id: 'objectId?',
    _partition: 'string',
    code_ons: 'string?',
    code_rs: 'string?',
    createdAt: 'date?',
    namear: 'string?',
    namefr_ons: 'string?',
    namefr_rs: 'string?',
    serverCreatedAt: 'date?',
    serverUpdatedAt: 'date?',
    updatedAt: 'date?',
    wilaya: 'string?',
    wilaya_id: 'objectId?',
    label: 'string?',
    value: 'string?',
  },
  primaryKey: '_id',
};

export const wilayaSchema = {
  name: 'wilaya',
  properties: {
    _id: 'objectId?',
    _partition: 'string',
    code_ons: 'string?',
    code_rs: 'string?',
    createdAt: 'date?',
    namear: 'string?',
    namefr_ons: 'string?',
    namefr_rs: 'string?',
    label: 'string?',
    value: 'string?',
    serverCreatedAt: 'date?',
    serverUpdatedAt: 'date?',
    updatedAt: 'date?',
  },
  primaryKey: '_id',
};
