import * as yup from 'yup';

export default function localite(t) {
  return [
    {
      title: `I. ${t('identify')}`,
      name: 'I',
      type: 'title',
      order: 0.1,
    },
    {
      title: t('residence_type'),
      type: 'select',
      name: 'ID4',
      label: t('residence_type'),
      order: 1,
      options: [
        {
          label: t('urbain'),
          value: 'urbain',
        },
        {
          label: t('rural'),
          value: 'rural',
        },
      ],
    },
    {
      title: t('zone_rural_moyens'),
      type: 'select',
      name: 'ID5',
      label: t('zone_rural_moyens'),
      order: 1.1,
      depends: 'ID4',
      answer: 'rural',
      options: [
        { label: t('nomad_pasto'), value: 'MR01' },
        { label: t('minie_pasto'), value: 'MR02' },
        { label: t('pasto_oas_oud'), value: 'MR03' },
        { label: t('lit_pech'), value: 'MR04' },
        { label: t('pasto_commerc'), value: 'MR05' },
        { label: t('trans_pasto'), value: 'MR06' },
        { label: t('agr_pasto'), value: 'MR07' },
        { label: t('flev_seneg'), value: 'MR08' },
        { label: t('cult_pulv'), value: 'MR09' },
      ],
    },
    {
      title: t('code_localite'),
      type: 'text',
      name: 'ID6',
      placeholder: t('code_localite'),
      order: 1.1,
      depends: 'ID4',
      answer: 'urbain',
    },
    {
      title: t('localite_name'),
      type: 'text',
      name: 'localeName',
      placeholder: t('localite_name'),
      order: 2,
    },
    {
      title: t('other_name'),
      type: 'text',
      name: 'otherName',
      placeholder: t('other_name'),
      order: 3,
    },
    {
      title: t('localite_status'),
      type: 'select',
      name: 'ID7',
      label: t('localite_status'),
      order: 4,
      options: [
        { label: t('permenent'), value: 'permenent' },
        { label: t('temporaire'), value: 'temporaire' },
      ],
    },
    {
      title: t('chef_comn_dist'),
      type: 'num',
      name: 'ID8',
      placeholder: t('chef_comn_dist'),
      order: 5,
    },
    {
      title: t('chef_mougha_dist'),
      type: 'num',
      name: 'ID9',
      placeholder: t('chef_mougha_dist'),
      order: 6,
    },
    {
      title: t('roude_dist'),
      type: 'num',
      name: 'ID10',
      placeholder: t('roude_dist'),
      order: 7,
    },
    {
      title: t('accessiblit_period'),
      type: 'num',
      name: 'ID11',
      placeholder: t('accessiblit_period'),
      order: 8,
    },

    {
      title: `II. ${t('laguages')}`,
      name: 'II',
      type: 'title',
      order: 0.2,
    },
    {
      title: t('dominant_lang'),
      type: 'select',
      name: 'LPA',
      label: t('dominant_lang'),
      order: 9,
      options: [
        { label: t('arab'), value: 'arab' },
        { label: t('polar'), value: 'polar' },
        { label: t('sonik'), value: 'sonik' },
        { label: t('wolof'), value: 'wolof' },
        { label: t('other'), value: 'other' },
      ],
    },
    {
      title: t('precise_lang'),
      type: 'text',
      name: 'otherlnag',
      placeholder: t('precise_lang'),
      order: 9.1,
      depends: 'LPA',
      answer: 'other',
    },
    {
      title: t('second_lang'),
      type: 'select',
      name: 'LPB',
      label: t('second_lang'),
      order: 10,
      options: [
        { label: t('arab'), value: 'arab' },
        { label: t('polar'), value: 'polar' },
        { label: t('sonik'), value: 'sonik' },
        { label: t('wolof'), value: 'wolof' },
        { label: t('none'), value: 'none' },
        { label: t('other'), value: 'other' },
      ],
    },
    {
      title: t('precise_second_lang'),
      type: 'text',
      name: 'othersecondlang',
      placeholder: t('precise_second_lang'),
      order: 10.1,
      depends: 'LPB',
      answer: 'other',
    },
    {
      title: `III. ${t('active_econominic')}`,
      name: 'III',
      type: 'title',
      order: 0.3,
    },
    {
      title: t('activ_econom'),
      type: 'select',
      multiple: true,
      name: 'activEconom',
      label: t('activ_econom'),
      order: 11,
      options: [
        { label: t('dieri'), value: 'dieri' },
        { label: t('bas_fond'), value: 'bas_fond' },
        { label: t('irrigue'), value: 'irrigue' },
        { label: t('maraichage'), value: 'maraichage' },
        { label: t('walo'), value: 'walo' },
        { label: t('decrue'), value: 'decrue' },
        { label: t('culture_oas'), value: 'culture_oas' },
        { label: t('elevage'), value: 'elevage' },
        { label: t('peche'), value: 'peche' },
        { label: t('industrie'), value: 'industrie' },
        { label: t('mines'), value: 'mines' },
        { label: t('commerce'), value: 'commerce' },
        { label: t('others'), value: 'others' },
      ],
    },
    {
      title: `IV. ${t('infras')}`,
      name: 'IV',
      type: 'title',
      order: 0.4,
    },
    {
      title: `IV.1 ${t('education')}`,
      name: 'edsub',
      type: 'subtitle',
    },
    {
      title: t('ecol_coran_num'),
      type: 'num',
      name: 'IV1E1',
      placeholder: t('ecol_coran_num'),
      order: 12.1,
    },
    {
      title: t('mahadr_num'),
      type: 'num',
      name: 'IV1E2',
      placeholder: t('mahadr_num'),
      order: 12.2,
    },
    {
      title: t('jardin_num'),
      type: 'num',
      name: 'IV1E3',
      placeholder: t('jardin_num'),
      order: 12.3,
    },
    {
      title: t('prim_complet_num'),
      type: 'num',
      name: 'IV1E4',
      placeholder: t('prim_complet_num'),
      order: 12.4,
    },
    {
      title: t('prim_complet_dist'),
      type: 'select',
      name: 'IV1E5',
      label: t('prim_complet_dist'),
      depends: 'IV1E4',
      isPositif: true,
      order: '12.4.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('prime_incomplet_num'),
      type: 'num',
      name: 'IV1E6',
      placeholder: t('prime_incomplet_num'),
      order: 12.5,
    },
    {
      title: t('prim_incomplet_dist'),
      type: 'select',
      name: 'IV1E7',
      label: t('prim_incomplet_dist'),
      depends: 'IV1E6',
      isPositif: true,
      order: '12.5.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('college_num'),
      type: 'num',
      name: 'IV1E8',
      placeholder: t('college_num'),
      order: 12.6,
    },
    {
      title: t('college_dist'),
      type: 'select',
      name: 'IV1E9',
      label: t('college_dist'),
      depends: 'IV1E8',
      isPositif: true,
      order: '12.6.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('lycee_num'),
      type: 'num',
      name: 'IV1E10',
      placeholder: t('lycee_num'),
      order: 12.7,
    },
    {
      title: t('lycee_dist'),
      type: 'select',
      name: 'IV1E11',
      label: t('lycee_dist'),
      depends: 'IV1E10',
      isPositif: true,
      order: '12.7.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('e_c_profesion_num'),
      type: 'num',
      name: 'IV1E12',
      placeholder: t('e_c_profesion_num'),
      order: 12.8,
    },
    {
      title: t('c_profes_dist'),
      type: 'select',
      name: 'IV1E13',
      label: t('c_profes_dist'),
      depends: 'IV1E12',
      isPositif: true,
      order: '12.8.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('class_alphab_num'),
      type: 'num',
      name: 'IV1E14',
      placeholder: t('class_alphab_num'),
      order: 12.9,
    },
    {
      title: t('others_num'),
      type: 'text',
      name: 'IV1E15',
      placeholder: t('others_num'),
      order: 12.1,
    },
    {
      title: `IV.2 ${t('health_infras')}`,
      name: 'healsub',
      type: 'subtitle',
      order: 0.2,
    },
    {
      title: t('health_unit_num'),
      type: 'num',
      name: 'IV2S1',
      placeholder: t('health_unit_num'),
      order: 13.1,
    },
    {
      title: t('health_unit_dist'),
      type: 'select',
      name: 'IV2S2',
      label: t('health_unit_dist'),
      depends: 'IV2S1',
      isPositif: true,
      order: '13.1.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('health_post_num'),
      type: 'num',
      name: 'IV2S3',
      placeholder: t('health_post_num'),
      order: 13.2,
    },
    {
      title: t('health_post_dist'),
      type: 'select',
      name: 'IV2S4',
      label: t('health_post_dist'),
      depends: 'IV2S3',
      isPositif: true,
      order: '13.2.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('health_centre_num'),
      type: 'num',
      name: 'IV2S5',
      placeholder: t('health_centre_num'),
      order: 13.3,
    },
    {
      title: t('health_center_dist'),
      type: 'select',
      name: 'IV2S6',
      label: t('health_center_dist'),
      depends: 'IV2S5',
      isPositif: true,
      order: '13.3.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('hospital_num'),
      type: 'num',
      name: 'IV2S7',
      placeholder: t('hospital_num'),
      order: 13.4,
    },
    {
      title: t('health_hospital_dist'),
      type: 'select',
      name: 'IV2S8',
      label: t('health_hospital_dist'),
      depends: 'IV2S7',
      isPositif: true,
      order: '13.4.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('pharmacy_num'),
      type: 'num',
      name: 'IV2S9',
      placeholder: t('pharmacy_num'),
      order: 13.5,
    },
    {
      title: t('health_pharmaci_dist'),
      type: 'select',
      name: 'IV2S10',
      label: t('health_pharmaci_dist'),
      depends: 'IV2S9',
      isPositif: true,
      order: '13.5.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('cabinet_num'),
      type: 'num',
      name: 'IV2S11',
      placeholder: t('cabinet_num'),
      order: 13.6,
    },
    {
      title: t('health_cabinet_dist'),
      type: 'select',
      name: 'IV2S12',
      label: t('health_cabinet_dist'),
      depends: 'IV2S11',
      isPositif: true,
      order: '13.6.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: t('clinic_num'),
      type: 'num',
      name: 'IV2S13',
      placeholder: t('clinic_num'),
      order: 13.7,
    },
    {
      title: t('health_clinic_dist'),
      type: 'select',
      name: 'IV2S14',
      label: t('health_clinic_dist'),
      depends: 'IV2S13',
      isPositif: true,
      order: '13.7.1',
      options: [
        { label: t('less_2km'), value: 'less_2km' },
        { label: t('less_5km'), value: 'less_5km' },
        { label: t('less_10km'), value: 'less_10km' },
        { label: t('more_10km'), value: 'more_10km' },
      ],
    },
    {
      title: `IV.3 ${t('water_infras')}`,
      name: 'watsub',
      type: 'subtitle',
      order: 0.3,
    },
    {
      title: t('puits_num'),
      type: 'num',
      name: 'puits',
      placeholder: t('puits_num'),
      order: 14.1,
    },
    {
      title: t('sondage_num'),
      type: 'num',
      name: 'sondage',
      placeholder: t('sondage_num'),
      order: 14.2,
    },
    {
      title: t('brone_num'),
      type: 'num',
      name: 'brone',
      placeholder: t('brone_num'),
      order: 14.3,
    },
    {
      title: t('aep_line_num'),
      type: 'num',
      name: 'AEP',
      placeholder: t('aep_line_num'),
      order: 14.4,
    },
    {
      title: t('SNDE'),
      type: 'select',
      name: 'SNDE',
      placeholder: t('SNDE'),
      order: 14.5,
      options: [
        { label: t('yes'), value: 'yes' },
        { label: t('no'), value: 'no' },
      ],
    },
    {
      title: t('others'),
      type: 'text',
      name: 'otherWater',
      placeholder: t('others'),
      order: 14.6,
    },
    {
      title: `IV.4 ${t('electric_infras')}`,
      name: 'electsub',
      type: 'subtitle',
      order: 0.4,
    },
    {
      title: t('electric_line'),
      type: 'select',
      name: 'electricLine',
      placeholder: t('electric_line'),
      order: 15.1,
      options: [
        { label: t('yes'), value: 'yes' },
        { label: t('no'), value: 'no' },
      ],
    },
    {
      title: t('solar'),
      type: 'num',
      name: 'solar',
      placeholder: t('solar'),
      order: 15.2,
    },
    {
      title: t('other'),
      type: 'text',
      name: 'otherEnergy',
      placeholder: t('other'),
      order: 15.3,
    },
    {
      title: `IV.5 ${t('socio_cult_infras')}`,
      type: 'subtitle',
      name: 'sociocultsub',
      order: 0.5,
    },
    {
      title: t('mosq_num'),
      type: 'num',
      name: 'mosqNum',
      placeholder: t('mosq_num'),
      order: 16.1,
    },
    {
      title: t('youn_house_num'),
      type: 'num',
      name: 'younHouseNum',
      placeholder: t('youn_house_num'),
      order: 16.2,
    },
    {
      title: t('CFPF_num'),
      type: 'num',
      name: 'CFPFNum',
      placeholder: t('CFPF_num'),
      order: 16.3,
    },
    {
      title: t('stad_num'),
      type: 'num',
      name: 'stadNum',
      placeholder: t('stad_num'),
      order: 16.4,
    },
    {
      title: t('other'),
      type: 'text',
      name: 'otherSocioCult',
      placeholder: t('other'),
      order: 16.5,
    },
    {
      title: `IV.6 ${t('economic_infras')}`,
      name: 'economicsub',
      type: 'subtitle',
    },
    {
      title: t('store'),
      type: 'num',
      name: 'store',
      placeholder: t('store'),
      order: 17.1,
    },
    {
      title: t('hebdo'),
      type: 'num',
      name: 'hebdo',
      placeholder: t('hebdo'),
      order: 17.2,
    },
    {
      title: t('betail'),
      type: 'num',
      name: 'betail',
      placeholder: t('betail'),
      order: 17.3,
    },
    {
      title: t('bettoir'),
      type: 'num',
      name: 'bettoir',
      placeholder: t('bettoir'),
      order: 17.4,
    },
    {
      title: t('parc_vaccination'),
      type: 'num',
      name: 'parcVaccination',
      placeholder: t('parc_vaccination'),
      order: 17.5,
    },
    {
      title: t('veterin'),
      type: 'num',
      name: 'veterin',
      placeholder: t('veterin'),
      order: 17.6,
    },
    {
      title: t('station'),
      type: 'num',
      name: 'station',
      placeholder: t('station'),
      order: 17.7,
    },
    {
      title: t('hotel'),
      type: 'num',
      name: 'hotel',
      placeholder: t('hotel'),
      order: 17.8,
    },
    {
      title: t('other'),
      type: 'text',
      name: 'otherEcoInfr',
      placeholder: t('other'),
      order: 17.9,
    },
    {},
    {},
    {},
    {
      title: `V. ${t('sages')}`,
      name: 'V',
      type: 'title',
    },

    {
      title: 'sages',
      type: 'fieldArray',
      name: 'sages',
      initialValues: { firstName: '', phoneNumber: '', nni: '' },
      fields: [
        {
          title: t('first_name'),
          type: 'text',
          name: 'firstName',
          placeholder: t('first_name'),
          order: 1,
        },
        {
          title: t('namef'),
          type: 'text',
          name: 'name',
          placeholder: t('namef'),
          order: 2,
        },
        {
          title: t('sex'),
          type: 'select',
          name: 'sex',
          label: t('sex'),
          options: [
            { label: t('male'), value: 'male' },
            { label: t('female'), value: 'female' },
          ],
          order: 3,
        },
        {
          title: t('nni'),
          type: 'num',
          name: 'nni',
          placeholder: t('nni'),
          order: 4,
        },
        {
          title: t('tel'),
          type: 'num',
          name: 'phone',
          placeholder: t('tel'),
          order: 5,
        },
      ],
    },
  ];
}

export const formValidationSchema = t =>
  yup.object().shape({
    ID4: yup.string().required(`1) ${t('residence_type')}`),
    ID5: yup.string().when(' ID4', {
      is: 'rural',
      then: yup.string().required(`1.1) ${t('zone_rural_moyens')}`),
    }),
    ID6: yup.string().when('residenceType', {
      is: 'urbain',
      then: yup.string().required(`1.1) ${t('code_localite')}`),
    }),
    localeName: yup.string().required(`2) ${t('localite_name')}`),
    otherName: yup.string(),
    ID7: yup.string().required(`4) ${t('localite_status')}`),
    ID8: yup.string().required(`5) ${t('chef_comn_dist')}`),
    ID9: yup.string().required(`6) ${t('chef_mougha_dist')}`),
    ID10: yup.string().required(`7) ${t('roude_dist')}`),
    ID11: yup.string().required(`8) ${t('accessiblit_period')}`),
    LPA: yup.string().required(`9) ${t('dominant_lang')}`),
    other: yup.string().when('LPA', {
      is: 'other',
      then: yup.string().required(`9.1) ${t('precise_lang')}`),
    }),
    LPB: yup
      .string()
      .required(`10) ${t('second_lang')}`)
      .when('LPA', (LPA, schema) =>
        schema.test({
          test: LPB => {
            console.log('LPA', LPA);
            console.log('LPB', LPB);
            return LPA?.slice(-1) !== LPB?.slice(-1);
          },
          message: t('languages_cant_be equal'),
        }),
      ),
    other: yup.string().when('LPB', {
      is: 'other',
      then: yup.string().required(`10.1) ${t('precise_second_lang')}`),
    }),
    activEconom: yup.array().required(`11) ${t('activ_econom')}`),
    IV1E1: yup.string().required(`12.1) ${t('ecol_coran_num')}`),
    IV1E2: yup.string().required(`12.2) ${t('mahadr_num')}`),
    IV1E3: yup.string().required(`12.3) ${t('jardin_num')}`),
    IV1E4: yup.string().required(`12.4) ${t('prim_complet_num')}`),
    IV1E6: yup.string().required(`12.5) ${t('prime_incomplet_num')}`),
    IV1E8: yup.string().required(`12.6) ${t('college_num')}`),
    IV1E10: yup.string().required(`12.7) ${t('lycee_num')}`),
    IV1E12: yup.string().required(`12.8) ${t('e_c_profesion_num')}`),
    IV1E14: yup.string().required(`12.9) ${t('class_alphab_num')}`),
    IV2S1: yup.string().required(`13.1) ${t('health_unit_num')}`),
    IV2S3: yup.string().required(`13.2) ${t('health_post_num')}`),
    IV2S5: yup.string().required(`13.3) ${t('health_centre_num')}`),
    IV2S7: yup.string().required(`13.4) ${t('hospital_num')}`),
    IV2S9: yup.string().required(`13.5) ${t('pharmacy_num')}`),
    IV2S11: yup.string().required(`13.6') ${t('cabinet_num')}`),
    IV2S13: yup.string().required(`13.7) ${t('clinic_num')}`),
    puits: yup.string().required(`14.1) ${t('puits_num')}`),
    sondage: yup.string().required(`14.2) ${t('sondage_num')}`),
    brone: yup.string().required(`14.3) ${t('brone_num')}`),
    AEP: yup.string().required(`14.4) ${t('aep_line_num')}`),
    SNDE: yup.string().required(`14.5) ${t('SNDE')}`),
    electricLine: yup.string().required(`15.1) ${t('electric_line')}`),
    solar: yup.string().required(`15.2) ${t('solar')}`),
    mosqNum: yup.string().required(`16.1) ${t('mosq_num')}`),
    younHouseNum: yup.string().required(`16.2) ${t('youn_house_num')}`),
    CFPFNum: yup.string().required(`16.3) ${t('CFPF_num')}`),
    stadNum: yup.string().required(`16.4) ${t('stad_num')}`),
    store: yup.string().required(`17.1) ${t('store')}`),
    hebdo: yup.string().required(`17.2) ${t('hebdo')}`),
    betail: yup.string().required(`17.3) ${t('betail')}`),
    bettoir: yup.string().required(`17.4) ${t('bettoir')}`),
    parcVaccination: yup.string().required(`17.5) ${t('parc_vaccination')}`),
    veterin: yup.string().required(`17.6) ${t('veterin')}`),
    station: yup.string().required(`17.7) ${t('station')}`),
    hotel: yup.string().required(`17.8) ${t('hotel')}`),
    IV1E5: yup.string().when('IV1E4', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`12.4.1) ${t('prim_complet_dist')}`),
    }),
    IV1E7: yup.string().when('IV1E6', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`12.5.1) ${t('prim_incomplet_dist')}`),
    }),
    IV1E9: yup.string().when('IV1E8', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`12.6.1) ${t('college_dist')}`),
    }),
    IV1E11: yup.string().when('IV1E10', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`12.7.1) ${t('lycee_dist')}`),
    }),
    IV1E13: yup.string().when('IV1E12', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`12.8.1) ${t('c_profes_dist')}`),
    }),
    IV2S2: yup.string().when('IV2S1', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.1.1) ${t('health_unit_dist')}`),
    }),
    IV2S4: yup.string().when('IV2S1', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.2.1) ${t('health_post_dist')}`),
    }),
    IV2S6: yup.string().when('IV2S5', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.3.1) ${t('health_post_dist')}`),
    }),
    IV2S8: yup.string().when('IV2S7', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.4.1) ${t('health_hospital_dist')}`),
    }),
    IV2S10: yup.string().when('IV2S9', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.5.1) ${t('health_pharmaci_dist')}`),
    }),
    IV2S12: yup.string().when('IV2S11', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.6.1) ${t('health_cabinet_dist')}`),
    }),
    IV2S14: yup.string().when('IV2S13', {
      is: val => !Number.isNaN(val) && parseInt(val, 10) <= 0,
      then: yup.string().required(`13.7.1) ${t('health_clinic_dist')}`),
    }),
  });

export const initialValues = {
  ID4: '',
  ID5: '',
  ID6: '',
  localeName: '',
  otherName: '',
  ID7: '',
  ID8: '',
  ID9: '',
  ID10: '',
  ID11: '',
  LPA: '',
  LPB: '',
  activEconom: '',
  IV1E1: '0',
  IV1E3: '0',
  IV1E6: '0',
  IV1E8: '0',
  IV1E10: '0',
  IV1E12: '0',
  IV1E14: '0',
  IV1E15: '0',
  IV2S1: '0',
  IV2S3: '0',
  IV2S5: '0',
  IV2S7: '0',
  IV2S9: '0',
  IV2S11: '0',
  IV2S13: '0',
  puits: '0',
  sondage: '0',
  brone: '0',
  AEP: '0',
  SNDE: '',
  otherWater: '',
  electricLine: '',
  solar: '',
  otherEnergy: '',
  mosqNum: '',
  younHouseNum: '',
  CFPFNum: '',
  stadNum: '',
  otherSocioCult: '',
  store: '',
  hebdo: '',
  betail: '',
  bettoir: '',
  parcVaccination: '',
  veterin: '',
  station: '',
  hotel: '',
  otherEcoInfr: '',
  IV1E5: '',
  IV1E7: '',
  IV1E9: '',
  IV1E11: '',
  IV1E13: '',
  IV2S2: '',
  IV2S4: '',
  IV2S6: '',
  IV2S8: '',
  IV2S10: '',
  IV2S12: '',
  IV2S14: '',
  sages: '',
};
