// @flow

const screenNames = {
  HistoryCiblage: 'HistoryCiblage',
  HistoryEnquete: 'HistoryEnquete',
  User: 'User',
  AddUser: 'AddUser',
  Users: 'Users',
  Home: 'Home',
  Scan: 'Scan',
  Ciblage: 'Ciblage',
  History: 'History',
  Listes: 'Listes',
  ViewListe: 'ViewListe',
  Details: 'Details',
  Login: 'Login',
  DataLoader: 'DataLoader',
  AddConcession: 'AddConcession',
  Zones: 'Zones',
  EditZone: 'EditZone',
  QuestionaireLocalite: 'QuestionaireLocalite',
  Enquete: 'Enquete',
  Concessions: 'Concessions',
  AddMenage: 'AddMenage',
  GeneralInfoModal: 'GeneralInfoModal',
  ZonesInfoModal: 'ZonesInfoModal',
  FinalSelection: 'FinalSelection',
  ConfirmSages: 'ConfirmSages',
  MenagesSelected: 'MenagesSelected',
  AddEnquete: 'AddEnquete',
  MenageMembres: 'MenageMembres',
  AddMembre: 'AddMembre',
  Localites: 'Localites',
  AddLocalite: 'AddLocalite',
  LocalitesToValidate: 'LocalitesToValidate',
  EditMenagePhoneNNI: 'EditMenagePhoneNNI',
  DiviseLocalite: 'DiviseLocalite',
  AddZone: 'AddZone',
  SeeQuotasLocalites: 'SeeQuotasLocalites',
  LocaliteIdentification: 'LocaliteIdentification',
  LocaliteInfras: 'LocaliteInfras',
  LocaliteSages: 'LocaliteSages',
  AddSage: 'AddSage',
  ResetSelectedZone: 'ResetSelectedZone',
  CorrectMenages: 'CorrectMenages',
  CorrectMenage: 'CorrectMenage',
  EditMenageSuper: 'EditMenageSuper',
  AddInfraction: 'AddInfraction',
  ListRouge: 'ListRouge',
  Identifications: 'Identifications',
  SubUsers: 'SubUsers',
};

export default screenNames;
